substitutions:
  device_name: "tempo-display-max7219"
  project_version: "1.0"

esphome:
  name: "${device_name}"
  friendly_name: tempoDisplay

esp8266:
  board: d1_mini

# Enable logging
logger:

ota:

wifi:
  ap: {} # This spawns an AP with the device name and mac address with no password.

spi:
  clk_pin: D5
  mosi_pin: D7

text_sensor:
  - platform: homeassistant
    name: "Tempo du jour"
    id: tempo_jour
    entity_id: sensor.rte_tempo_couleur_actuelle

  - platform: homeassistant
    name: "Tempo du lendemain"
    id: tempo_demain
    entity_id: sensor.rte_tempo_prochaine_couleur

display:
  - platform: max7219digit
    id: matrixLed
    cs_pin: D6
    num_chips: 4
    intensity: 1
    lambda: |-
      it.strftime(4, 0, id(digit_font), "%H:%M", id(hass_time).now());
      if (id(tempo_jour).state == "Bleu") {
        id(tempoBlueToday).execute();
      } else if (id(tempo_jour).state == "Blanc") {
        id(tempoWhiteToday).execute();
      } else if (id(tempo_jour).state == "Rouge") {
        id(tempoRedToday).execute();
      }
      if (id(tempo_demain).state == "Bleu") {
        id(tempoBlueTomorrow).execute();
      } else if (id(tempo_demain).state == "Blanc") {
        id(tempoWhiteTomorrow).execute();
      } else if (id(tempo_demain).state == "Rouge") {
        id(tempoRedTomorrow).execute();
      }      

font:
  - file: "fonts/pixelmix.ttf"
    id: digit_font
    size: 8

time:
  - platform: homeassistant
    timezone: "Europe/Paris"
    id: hass_time

captive_portal:

script:
  - id: tempoBlueToday
    then:
      lambda: |-
        matrixLed->draw_pixel_at(0, 0, COLOR_ON);
        matrixLed->draw_pixel_at(0, 1, COLOR_ON);
        matrixLed->draw_pixel_at(1, 0, COLOR_ON);
        matrixLed->draw_pixel_at(1, 1, COLOR_ON);
        matrixLed->draw_pixel_at(0, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 6, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 6, COLOR_OFF);

  - id: tempoWhiteToday
    then:
      lambda: |-
        matrixLed->draw_pixel_at(0, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 4, COLOR_ON);
        matrixLed->draw_pixel_at(1, 4, COLOR_ON);
        matrixLed->draw_pixel_at(0, 3, COLOR_ON);
        matrixLed->draw_pixel_at(1, 3, COLOR_ON);
        matrixLed->draw_pixel_at(0, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 6, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 6, COLOR_OFF);

  - id: tempoRedToday
    then:
      lambda: |-
        matrixLed->draw_pixel_at(0, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(1, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(0, 7, COLOR_ON);
        matrixLed->draw_pixel_at(1, 7, COLOR_ON);
        matrixLed->draw_pixel_at(0, 6, COLOR_ON);
        matrixLed->draw_pixel_at(1, 6, COLOR_ON);

  - id: tempoBlueTomorrow
    then:
      lambda: |-
        matrixLed->draw_pixel_at(31, 0, COLOR_ON);
        matrixLed->draw_pixel_at(30, 0, COLOR_ON);
        matrixLed->draw_pixel_at(31, 1, COLOR_ON);
        matrixLed->draw_pixel_at(30, 1, COLOR_ON);
        matrixLed->draw_pixel_at(31, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 6, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 6, COLOR_OFF);

  - id: tempoWhiteTomorrow
    then:
      lambda: |-
        matrixLed->draw_pixel_at(31, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 4, COLOR_ON);
        matrixLed->draw_pixel_at(30, 4, COLOR_ON);
        matrixLed->draw_pixel_at(31, 3, COLOR_ON);
        matrixLed->draw_pixel_at(30, 3, COLOR_ON);
        matrixLed->draw_pixel_at(31, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 7, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 6, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 6, COLOR_OFF);

  - id: tempoRedTomorrow
    then:
      lambda: |-
        matrixLed->draw_pixel_at(31, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 0, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 1, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 4, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(30, 3, COLOR_OFF);
        matrixLed->draw_pixel_at(31, 7, COLOR_ON);
        matrixLed->draw_pixel_at(30, 7, COLOR_ON);
        matrixLed->draw_pixel_at(31, 6, COLOR_ON);
        matrixLed->draw_pixel_at(30, 6, COLOR_ON);
